
title: تجربه باز / open experience
description: در ستایش تجربه کردن و یادگرفتن همیشگی
author: کیاوش
language: Farsi

url: http://kiavash.one/
root: /

icon: /static/img/logo.png
css: kiavone.css

static: /static/
imageurl: /img/

default_extension: md

permalink: :year/:mounth/:day/:title/

default_markup: mmd

post_num: 5
archive_post_num: 5
feed_output: atom.xml

template: opex
google_analytics: UA-114921404-1

lists:
 - tags
 - categories

namespace:

plugins:
 - Jdate

links:
 -  name: امیر مهرانی
    url: http://thecoach.ir/

 -  name: طه
    url: https://blog.dutymess.ir/

 -  name: سالار کابلی
    url: https://sallar.me/farsi/

 -  name: مهدی صادقی
    url: https://mehdix.ir/
